# Generated by Django 3.2 on 2021-05-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='dateAdded',
            new_name='timestamp',
        ),
    ]
