# Generated by Django 3.1.7 on 2021-03-26 09:42

import RoutePlanner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoutePlanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(default='', max_length=450, validators=[RoutePlanner.models.validate_presence]),
        ),
        migrations.AddField(
            model_name='route',
            name='points',
            field=models.TextField(default='', validators=[RoutePlanner.models.validate_presence]),
        ),
        migrations.AlterField(
            model_name='route',
            name='title',
            field=models.CharField(default='', max_length=50, validators=[RoutePlanner.models.validate_presence]),
        ),
    ]
