# Generated by Django 3.1.7 on 2021-05-03 15:21

import RoutePlanner.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RoutePlanner', '0003_auto_20210426_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='length',
            field=models.FloatField(default=0.0, validators=[RoutePlanner.models.validate_length]),
        ),
    ]
