# Generated by Django 3.1.7 on 2021-04-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
