# Generated by Django 3.2 on 2021-04-28 12:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0003_route_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=[], size=None),
            preserve_default=False,
        ),
    ]
