# Generated by Django 3.2 on 2021-04-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0004_auto_20210428_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
