# Generated by Django 3.1.7 on 2021-05-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0005_route_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
